Fix Bug And Fix Layout
TeamBeMe/BeMeAndroid pull request #628
Opened 2021-03-25 11:47 UTC by yjooooo

- Firebase 로그 코드 위치 수정
- 전체 뷰에서 더보기 위아래 margin 수정
- MyWrite 잠금 버튼 한번만 눌리는 문제 해결

2021-03-25 11:55 UTC, l2hyunwoo commented on app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
> +        }
```kotlin
fun String.logAnalyticsEvent() {
        Firebase.analytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW) {
            param(FirebaseAnalytics.Param.SCREEN_NAME, this)
            param(FirebaseAnalytics.Param.SCREEN_CLASS, "MainActivity")
        }
}
```

2021-03-25 11:58 UTC, l2hyunwoo requested changes
좋습니다. 공통적인 부분만 뽑으시면 될 것 같아요.

2021-03-25 11:58 UTC, l2hyunwoo commented on app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
> +        }
```kotlin
fun String.logAnalyticsEvent() {
        Firebase.analytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW) {
            param(FirebaseAnalytics.Param.SCREEN_NAME, this)
            param(FirebaseAnalytics.Param.SCREEN_CLASS, "MainActivity")
        }
}
```

2021-03-30 07:58 UTC, yjooooo commented on app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
> +        }
저기서 this를 String으로 잡는게 아니라 그 바로위의 Firebase인가 Firebase.analytics를 잡으니까
아래처럼 쓸게유

```kotlin
fun recordScreen(screenName: String) {
        Firebase.analytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW) {
            param(FirebaseAnalytics.Param.SCREEN_NAME, screenName)
            param(FirebaseAnalytics.Param.SCREEN_CLASS, "MainActivity")
        }
    }
```

2021-03-30 08:08 UTC, merged